version: '3.3'
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - './data:/data'
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=ch_all
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=m
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    image: haugene/transmission-openvpn