version: '3.3'
services:
  flexget:
    image: cpoppema/docker-flexget
    container_name: flexget
    environment:
      - PUID=65534
      - PGID=65534
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission
      - TZ=America/Chicago
      - FLEXGET_LOG_LEVEL=debug
    volumes:
      - './flexget-home:/config'
      - '${TRANSMISSION_DIR:-./data}:/downloads'
    ports:
      - 5050:5050
    restart: unless-stopped

  transmission-openvpn:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=ch_all
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=m
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - '${TRANSMISSION_DIR:-./data}:/data'
    ports:
      - '9091:9091'
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
