plex_version: 1.13.5.5291-6fa5e50a8
plex_file: "plexmediaserver_{{ plex_version }}_amd64.deb"

ums_version: 6.7.2
ums_dir: "{{ apps_dir }}/ums-{{ ums_version }}"
ums_file: "UMS-{{ ums_version }}.tgz"

config_files:
  plex:
    src: plex/Preferences.xml
    dest: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml
    owner: plex
    group: plex
    mode: "0600"
  ums_configuration:
    src: ums/UMS.conf
    dest: "{{ ums_dir }}/UMS.conf"
    owner: root
    group: root
    mode: "0622"
  ums_startup_script:
    src: ums/UMS
    dest: /etc/init.d/UMS
    owner: root
    group: root
    mode: "0755"