version: '3.3'
services:
  flexget:
    container_name: flexget
    image: cpoppema/docker-flexget
    environment:
      - PUID=65534
      - PGID=65534
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission
      - TZ=America/Chicago
      - FLEXGET_LOG_LEVEL=debug
    volumes:
      - '${FLEXGET_DIR:-./flexget}/config:/config'
      - '${TRANSMISSION_DIR:-./transmission}/downloads:/downloads'
    ports:
      - 5050:5050
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=192.168.254.11
    volumes:
      - '${JELLYFIN_DIR:-./jellyfin}/config:/config'
      - '${MOVIES_DIR:-./jellyfin/movies}:/data/movies'
      - '${TV_DIR:-./jellyfin/tv}:/data/tvshows'
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=65534
      - PGID=65534
      - VERSION=docker
    volumes:
      - '${PLEX_DIR:-./plex}/config:/config'
      - '${MOVIES_DIR:-./plex/movies}:/movies'
      - '${TV_DIR:-./plex/tv}:/tv'
    restart: unless-stopped

  transmission-openvpn:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      # Temporary until https://github.com/haugene/vpn-configs-contrib/pull/305 is reverted
      - OPENVPN_PROVIDER=MULLVAD
      - GITHUB_CONFIG_SOURCE_REPO=divadsn/vpn-configs-contrib-mullvad
      - OPENVPN_CONFIG=ch_all # us_den
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=m
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=999
      - TRANSMISSION_QUEUE_STALLED_ENABLED=false
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - '${TRANSMISSION_DIR:-./transmission}:/data'
    ports:
      - '9091:9091'
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
