version: '3.3'
services:
  flexget:
    container_name: flexget
    image: cpoppema/docker-flexget
    environment:
      - PUID=65534
      - PGID=65534
      - WEB_PASSWD=yourhorriblesecret
      - TORRENT_PLUGIN=transmission
      - TZ=America/Chicago
      - FLEXGET_LOG_LEVEL=debug
    volumes:
      - '${FLEXGET_DIR:-./flexget}/config:/config'
      - '${TRANSMISSION_DIR:-./transmission}/downloads:/downloads'
    ports:
      - 5050:5050
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=65534
      - PGID=65534
      - VERSION=docker
    volumes:
      - '${PLEX_DIR:-./plex}/config:/config'
      - '${MOVIES_DIR:-./plex/movies}:/movies'
      - '${TV_DIR:-./plex/tv}:/tv'
    restart: unless-stopped

  transmission-openvpn:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=ch_all
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=m
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=999
      - TRANSMISSION_QUEUE_STALLED_ENABLED=false
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - '${TRANSMISSION_DIR:-./transmission}:/data'
    ports:
      - '9091:9091'
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
