transmission_ip_leak_magnet_link: magnet:?xt=urn:btih:2a4e3807a937f43390d0d971b58b332be5221ac2&tr=https://ipleak.net/announce.php%3Fh%3D2a4e3807a937f43390d0d971b58b332be5221ac2&dn=ipleak.net+torrent+detection

directories:
  transmission-daemon:
    path: "{{ transmission_torrent_dir }}"
    owner: root
    group: root
    mode: "0777"
