transmission_bind_ipv4: "{{ vpn_ipaddress }}"
transmission_blocklist_enabled: false
transmission_blocklist_url: http://list.iblocklist.com/?list=bt_level2&fileformat=p2p&archiveformat=gz
transmission_ip_leak_magnet_link: magnet:?xt=urn:btih:2a4e3807a937f43390d0d971b58b332be5221ac2&tr=https://ipleak.net/announce.php%3Fh%3D2a4e3807a937f43390d0d971b58b332be5221ac2&dn=ipleak.net+torrent+detection
transmission_ratio_limit: 0
transmission_torrent_dir: "{{ apps_dir }}/downloads"
transmission_watch_dir: "{{ transmission_torrent_dir }}/queue"

directories:
  transmission-daemon:
    path: "{{ transmission_torrent_dir }}"
    owner: debian-transmission
    group: debian-transmission
    mode: "0777"

config_files:
  netconfig:
    src: netplan/01-netcfg.yaml
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: "0644"
  transmission-daemon-settings:
    src: transmission-daemon/settings.json
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: "0600"