---
- include_role:
    name: common

- include_vars: main.yml

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'transmission-cli' ]

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Update apt and install docker-compose
  apt: update_cache=yes name={{ item }} state=latest
  loop: [ 'docker-ce', 'docker-compose' ]

- name: Copy configuration files
  template: src={{ item }} dest={{ apps_dir }}/{{ item }} owner=root group=root mode=0777
  loop: [ 'docker-compose.yml', 'production.yml' ]

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ apps_dir }}"
    files:
      - docker-compose.yml
      - production.yml
  environment:
    TRANSMISSION_DIR: "{{ transmission_torrent_dir }}"
    VPN_USERNAME: "{{ vpn_username }}"

- name: Add ipleak.net torrent to transmission
  shell: 'transmission-remote -a "{{ transmission_ip_leak_magnet_link }}"'