---
- include_role:
    name: common

- include_vars: main.yml

- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
    - transmission-daemon
    - transmission-cli

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Shutdown applications for configuration
  service: name={{item}} state=stopped
  with_items:
    - transmission-daemon

- name: Copy configuration files
  template: src={{ item.value.src }} dest={{ item.value.dest }} owner={{ item.value.owner }} group={{ item.value.group }} mode={{ item.value.mode }}
  with_dict: "{{ config_files }}"

- name: Startup applications
  service: name={{item}} state=started
  with_items:
    - transmission-daemon

- name: Add ipleak.net torrent to transmission
  shell: 'transmission-remote -a "{{ transmission_ip_leak_magnet_link }}"'