---
- include_role:
    name: common

- include_vars: main.yml

- name: Install jenkins apt repository key
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: Install jenkins apt repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
    - jenkins
    - python-jenkins
    - python-lxml
    - virtualenv # Required by flexget
    - youtube-dl
    # Required by photo/video processing
    - libimage-exiftool-perl
    - par2

- name: Shutdown applications for configuration
  service: name={{item}} state=stopped
  with_items:
    - jenkins

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Copy configuration files
  template: src={{ item.value.src }} dest={{ item.value.dest }} owner={{ item.value.owner }} group={{ item.value.group }} mode={{ item.value.mode }}
  with_dict: "{{ config_files }}"

- name: Startup applications
  service: name={{item}} state=started
  with_items:
    - jenkins

- name: Wait until Jenkins web interface is available
  wait_for: "host=localhost port=8080 state=present delay=30 timeout=300"

- name: Install plugins
  jenkins_plugin: name={{ item }}
  with_items:
    - git
    - workflow-aggregator
    - htmlpublisher

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait until Jenkins web interface is available
  wait_for: "host=localhost port=8080 state=present delay=30 timeout=300"

- name: Configure jobs
  jenkins_job: config="{{ lookup('template', 'job-config.xml') }}" name='{{ item.key }}' url=http://localhost:8080
  with_dict: "{{ jobs }}"