---
- include_role:
    name: common

- include_vars: main.yml

- name: Install list of packages
  apt: name={{item}} state=present
  with_items:
    - mysql-server-5.7
    - nfs-kernel-server
    - ntp
    - samba

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Copy configuration files
  template: src={{ item.value.src }} dest={{ item.value.dest }} owner={{ item.value.owner }} group={{ item.value.group }} mode={{ item.value.mode }}
  with_dict: "{{ config_files }}"