---
- include_role:
    name: common

- include_vars: main.yml

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Install list of packages
  apt:
    name: ['nfs-kernel-server', 'ntp', 'samba']
    state: present

- name: Copy configuration files
  template: src={{ item.value.src }} dest={{ item.value.dest }} owner={{ item.value.owner }} group={{ item.value.group }} mode={{ item.value.mode }}
  with_dict: "{{ config_files }}"

- name: RAID failure check cron
  cron:
    name: "check for RAID failure"
    special_time: hourly
    job: '[ $(cat /proc/mdstat | grep "UUUUU" | wc -l) = "4" ] || DegradedRAIDArrayFound'

- name: RAID status cron
  cron:
    name: "email raid status"
    special_time: weekly
    job: 'cat /proc/mdstat | mail -s "RAID Status" {{ cron_email }}'