mysql_dir: "{{ apps_dir }}/mysql"

directories:
  apps:
    path: "{{ apps_dir }}"
    owner: root
    group: root
    mode: "0777"
  mysql:
    path: "{{ mysql_dir }}"
    owner: root
    group: root
    mode: "0700"

config_files:
  mdadm:
    src: maxresync.conf
    dest: /etc/sysctl.d/maxresync.conf
    owner: root
    group: root
    mode: "0622"
  nfs-exports:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: "0622"
  samba:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0622"