---
- include_vars: main.yml
- include_vars: vault.yml

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Create a timezone symbolic link
  file:
    src: '{{ timezone_file }}'
    dest: /etc/localtime
    owner: root
    group: root
    state: link
    force: true

- name: Copy timezone
  template: src=timezone dest=/etc/timezone owner=root group=root mode=0622

- name: Install list of packages
  apt:
    name: ['screen', 'git', 'tmpreaper', 'wget']
    state: present

- name: Add destination email for cron failures
  cron:
    name: MAILTO
    env: yes
    job: '{{ cron_email }}'

- name: cron job to clean tmp dir
  cron:
    name: "clean tmp dir"
    special_time: daily
    job: "[ -d /tmp/cron ] && /usr/sbin/tmpreaper --runtime 120 1d /tmp/cron > /dev/null"
