---
- include_role:
    name: common

- include_vars: main.yml

- name: Create necessary directories
  file: path={{ item.value.path }} owner={{ item.value.owner }} group={{ item.value.group }} state=directory mode={{ item.value.mode }}
  with_dict: "{{ directories }}"

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common',
          'python3-pip', 'virtualenv', 'python3-setuptools', 'transmission-cli', 'ffmpeg',
          'openjdk-16-jdk',
    # Required by photo/video processing
          'libimage-exiftool-perl', 'par2', 'rename'
  ]

- name: Install yt-dlp
  shell: 'python3 -m pip install -U yt-dlp'

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Update apt and install docker-compose
  apt: update_cache=yes name={{ item }} state=latest
  loop: [ 'docker-ce', 'docker-compose' ]

- name: Copy configuration files
  template: src={{ item }} dest={{ apps_dir }}/{{ item }} owner=root group=root mode=0777
  loop: [ 'docker-compose.yml', 'flexget/config.yml' ]

- name: Copy Docker env file
  template: src=dockerenv dest="{{ apps_dir }}/.env" owner=root group=root mode=0777

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ apps_dir }}"
    tls_hostname: localhost
    files:
      - docker-compose.yml

- name: Create transmission symbolic link
  file:
    src: '{{ transmission_torrent_dir }}/transmission-home'
    dest: '{{ apps_dir }}/transmission'
    state: link

- name: Copy cron scripts
  template: src="cron/{{ item }}" dest={{ cron_jobs_dir }}/{{ item }} owner=root group=root mode=0700
  loop: [ 'moveTVShows.sh', 'processPhotosAndVideos.sh', 'sharingVideoDownloads.sh' ]

- name: cron job to move completed downloads
  cron:
    name: "move completed downloads"
    special_time: hourly
    job: "{{ cron_jobs_dir }}/moveTVShows.sh > /dev/null"

- name: cron job for photo and video processing
  cron:
    name: "photo and video processing"
    special_time: daily
    job: "{{ cron_jobs_dir }}/processPhotosAndVideos.sh > /dev/null"

- name: cron job for sharing video downloads
  cron:
    name: "download sharing videos"
    special_time: daily
    job: "{{ cron_jobs_dir }}/sharingVideoDownloads.sh > /dev/null"

- name: Add ipleak.net torrent to transmission
  shell: 'transmission-remote -a "{{ transmission_ip_leak_magnet_link }}"'