directories:
  jenkins-gradle:
    path: /var/lib/jenkins/.gradle
    owner: jenkins
    group: jenkins
    mode: "0755"

config_files:
  jenkins-config:
    src: config.xml
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: "0644"
  jenkins-service-config:
    src: jenkins
    dest: /etc/default/jenkins
    owner: jenkins
    group: jenkins
    mode: "0644"
  gradle_properties:
    src: gradle.properties
    dest: /var/lib/jenkins/.gradle/gradle.properties
    owner: jenkins
    group: jenkins
    mode: "0600"

jobs:
  Video_Sharing_Downloads:
    repository_url: https://github.com/dustinjohnson13/jenkins-jobs.git
    frequency: '@daily'
    poll_frequency: ''
    pipeline_file: 'Video_Sharing_Downloads_Jenkinsfile'