directories:
  jenkins-gradle:
    path: /var/lib/jenkins/.gradle
    owner: jenkins
    group: jenkins
    mode: "0755"

config_files:
  jenkins-config:
    src: config.xml
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: "0644"
  jenkins-service-config:
    src: jenkins
    dest: /etc/default/jenkins
    owner: jenkins
    group: jenkins
    mode: "0644"
  gradle_properties:
    src: gradle.properties
    dest: /var/lib/jenkins/.gradle/gradle.properties
    owner: jenkins
    group: jenkins
    mode: "0600"

jobs:
  Cox_Data_Usage_Retriever:
    repository_url: https://github.com/dustinjohnson13/cox-data-usage-retriever.git
    frequency: 'H 8 * * *'
    pipeline_file: 'Jenkinsfile'
  Craigslist_Search:
    repository_url: https://github.com/dustinjohnson13/craigslist.git
    frequency: ''
    pipeline_file: 'Jenkinsfile'
  Download_TV_Shows_Via_FlexGet:
    repository_url: https://github.com/dustinjohnson13/flexget.git
    frequency: '@hourly'
    pipeline_file: 'Jenkinsfile'
  Nightly_Photo_and_Video_Processing:
    repository_url: https://github.com/dustinjohnson13/photo_and_video_processing.git
    frequency: '@daily'
    pipeline_file: 'Jenkinsfile'
  RAID_Failure_Check:
    repository_url: https://github.com/dustinjohnson13/jenkins-jobs.git
    frequency: '@hourly'
    pipeline_file: 'RAID_Failure_Check_Jenkinsfile'
  RAID_Status:
    repository_url: https://github.com/dustinjohnson13/jenkins-jobs.git
    frequency: 'H 5 * * 1'
    pipeline_file: 'RAID_Status_Jenkinsfile'
  Set_Torrent_Seed_Ratio:
    repository_url: https://github.com/dustinjohnson13/jenkins-jobs.git
    frequency: ''
    pipeline_file: 'Set_Torrent_Seed_Ratio_Jenkinsfile'
  Video_Sharing_Downloads:
    repository_url: https://github.com/dustinjohnson13/jenkins-jobs.git
    frequency: '@daily'
    pipeline_file: 'Video_Sharing_Downloads_Jenkinsfile'
  CodeMemo_Client:
    repository_url: https://github.com/dustinjohnson13/codememo-client.git
    frequency: 'H/15 * * * *'
    pipeline_file: 'Jenkinsfile'
  CodeMemo_Server:
    repository_url: https://github.com/dustinjohnson13/codememo-server.git
    frequency: 'H/15 * * * *'
    pipeline_file: 'Jenkinsfile'