cron_email: "{{ sendmail_username }}"
cron_jobs_dir: "/var/cron"
timezone: "America/Chicago"
timezone_file: "/usr/share/zoneinfo/{{ timezone }}"

data_dir: /data
apps_dir: "{{ data_dir }}/apps"

archives_dir: "{{ data_dir }}/archives"
movies_dir: "{{ archives_dir }}/video/movies"
tv_dir: "{{ archives_dir }}/video/tv"

downloads_dir: "{{ apps_dir }}/downloads"
completed_downloads_dir: "{{ downloads_dir }}/completed"
incomplete_downloads_dir: "{{ downloads_dir }}/incomplete"

directories:
  completed_downloads:
    path: "{{ completed_downloads_dir }}"
    owner: root
    group: root
    mode: "0777"
  cron_jobs:
    path: "{{ cron_jobs_dir }}"
    owner: root
    group: root
    mode: "0700"
  incomplete_downloads:
    path: "{{ incomplete_downloads_dir }}"
    owner: root
    group: root
    mode: "0777"