data_dir: /data
apps_dir: "{{ data_dir }}/apps"

archives_dir: "{{ data_dir }}/archives"
education_videos_dir: "{{ archives_dir }}/video/education"
movies_dir: "{{ archives_dir }}/video/movies"
music_dir: "{{ archives_dir }}/audio/music"
tv_dir: "{{ archives_dir }}/video/tv"

downloads_dir: "{{ apps_dir }}/downloads"
completed_downloads_dir: "{{ downloads_dir }}/complete"
incomplete_downloads_dir: "{{ downloads_dir }}/incomplete"

directories:
  completed_downloads:
    path: "{{ completed_downloads_dir }}"
    owner: root
    group: root
    mode: "0777"
  incomplete_downloads:
    path: "{{ incomplete_downloads_dir }}"
    owner: root
    group: root
    mode: "0777"